# TCL File Generated by Component Editor 13.0sp1
# Sun Jun 21 17:47:44 CST 2026
# DO NOT MODIFY


# 
# AvbusbCtrl "AvbusbCtrl" v1.0
# Shih-An Li 2026.06.21.17:47:44
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module AvbusbCtrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME AvbusbCtrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Shih-An Li"
set_module_property DISPLAY_NAME AvbusbCtrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvbusbCtrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file AvbusbCtrl.v VERILOG PATH ../ip/AvbusbCtrl.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter fifodepth INTEGER 256
set_parameter_property fifodepth DEFAULT_VALUE 256
set_parameter_property fifodepth DISPLAY_NAME fifodepth
set_parameter_property fifodepth TYPE INTEGER
set_parameter_property fifodepth UNITS None
set_parameter_property fifodepth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property fifodepth HDL_PARAMETER true
add_parameter fifowidth INTEGER 8
set_parameter_property fifowidth DEFAULT_VALUE 8
set_parameter_property fifowidth DISPLAY_NAME fifowidth
set_parameter_property fifowidth TYPE INTEGER
set_parameter_property fifowidth UNITS None
set_parameter_property fifowidth ALLOWED_RANGES -2147483648:2147483647
set_parameter_property fifowidth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true
set_interface_property clockreset EXPORT_OF ""
set_interface_property clockreset PORT_NAME_MAP ""
set_interface_property clockreset SVD_ADDRESS_GROUP ""

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true
set_interface_property clockreset_reset EXPORT_OF ""
set_interface_property clockreset_reset PORT_NAME_MAP ""
set_interface_property clockreset_reset SVD_ADDRESS_GROUP ""

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clockreset
set_interface_property s1 associatedReset clockreset_reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
add_interface_port s1 avs_s1_byteenable byteenable Input 4
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq_s1
# 
add_interface irq_s1 interrupt end
set_interface_property irq_s1 associatedAddressablePoint s1
set_interface_property irq_s1 associatedClock clockreset
set_interface_property irq_s1 associatedReset clockreset_reset
set_interface_property irq_s1 ENABLED true
set_interface_property irq_s1 EXPORT_OF ""
set_interface_property irq_s1 PORT_NAME_MAP ""
set_interface_property irq_s1 SVD_ADDRESS_GROUP ""

add_interface_port irq_s1 avs_s1_irq irq Output 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clockreset
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export avs_export_dp_pu_o export Output 1
add_interface_port export avs_export_tx_en_o export Output 1
add_interface_port export avs_export_dp_tx_o export Output 1
add_interface_port export avs_export_dn_tx_o export Output 1
add_interface_port export avs_export_dp_rx_i export Input 1
add_interface_port export avs_export_dn_rx_i export Input 1
add_interface_port export avs_export_clk50_i export Input 1

